env:
  browser: true
  es2023: true
  node: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:vitest/recommended
  - plugin:tailwindcss/recommended
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 2023
  sourceType: module
plugins:
  - "@typescript-eslint"
  - react
  - vitest
root: true
settings:
  react:
    version: detect
