name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - .eslintrc.yaml
      - .github/workflows/build-deploy-pages.yaml
      - .github/workflows/reusable-build-deploy-pages.yaml
      - .prettierrc.yaml
      - app
      - components
      - public
      - services
      - next.config.js
      - package*.json
      - postcss.config.js
      - tailwind.config.js
      - tsconfig.json
      - vitest.config.js

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  use-build-deploy-pages:
    uses: ./.github/workflows/reusable-build-deploy-pages.yaml
    secrets:
      GIST_PAT: ${{ secrets.GIST_PAT }}
