name: Fetch Pump It Up Phoenix My Best Scores

on:
  schedule:
    - cron: "0 23 * * *"

permissions:
  contents: read
  pages: write
  id-token: write

env:
  NODE_VERSION: "20.10.0"

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: .next/cache
          key: ${{ runner.os }}-piuphoenixmybestportal-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: ${{ runner.os }}-piuphoenixmybestportal-${{ hashFiles('**/package-lock.json') }}-

      - name: Install dependencies
        run: npm ci

      - name: Fetch Scores
        run: npm run fetch
        env:
          GIST_PAT: ${{ secrets.GIST_PAT }}
          PIU_PHOENIX_EMAIL: ${{ vars.PIU_PHOENIX_EMAIL }}
          PIU_PHOENIX_PASSWORD: ${{ secrets.PIU_PHOENIX_PASSWORD }}

  use-build-deploy-pages:
    uses: ./.github/workflows/reusable-build-deploy-pages.yaml
    needs: fetch
    secrets:
      GIST_PAT: ${{ secrets.GIST_PAT }}
